### ISSUE TITLE
puppeteer-core renderer

### ISSUE THREAD

**Issue by GauthierPLM** [Tofandel/prerenderer#43]
I would like to run prerender-spa-plugin on [zeit.co](https://zeit.co) with puppeteer-core (and [chrome-aws-lambda](https://www.npmjs.com/package/chrome-aws-lambda) as chromium instance) instead of puppeteer to be able to generate my pages on zeit.co.

As explained in #42, chrome is not able to initialize itself on zeit.co because of a missing dependencies. I contacted zeit.co support which recommended me to use [chrome-aws-lambda](https://www.npmjs.com/package/chrome-aws-lambda). However, it requires to use puppeteer-core instead of puppeteer.

Would it be possible to have a renderer which works with puppeteer-core instead of puppeteer?

**Comment by rudolfbyker** [comment]
I actually think the `prerenderer` package should ONLY use `puppeteer-core`. From the puppeteer docs:

> However, you should use puppeteer-core if:
> - you're building another end-user product or library atop of DevTools protocol. For example, one might build a PDF generator using puppeteer-core and write a custom install.js script that downloads headless_shell instead of Chromium to save disk space.
> - you're bundling Puppeteer to use in Chrome Extension / browser with the DevTools protocol where downloading an additional Chromium binary is unnecessary.
> - you're building a set of tools where puppeteer-core is one of the ingredients and you want to postpone install.js script execution until Chromium is about to be used.
>
> When using puppeteer-core, remember to change the include line:
> 
> const puppeteer = require('puppeteer-core');
> 
> You will then need to call puppeteer.connect([options]) or puppeteer.launch([options]) with an explicit executablePath option.

The `executablePath` should be provided by the code that uses `prerenderer`, thereby allowing the user to manage their own Chromium instances using AWS or something like https://github.com/cenfun/puppeteer-chromium-resolver

**Comment by JoshTheDerf** [comment]
Noted, will try and incorporate this in a future version.

**Comment by Tofandel** [comment]
You could in theory just set the option `puppeteerExecutablePath` in your package.json and it will act as if it was puppeter-core and not download chromium 

See https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer/src/getConfiguration.ts#L33 for reference and other ways to set this option
