### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by JoshTheDerf** [Tofandel/prerenderer#57]
As support for server-side rendering has matured, I've had little reason to revisit pre-rendering in any of my projects. As a result, I've had no need of this library for my own purposes and have let it fall by the wayside.

At this point, I'd be happy to transfer ownership of the project to someone who still has active use for pre-rendering and would be willing to bring this repo up back up to date.

Reply here if you're interested. :)

**Comment by Tofandel** [comment]
Bit late, but I was about to fork the project to start updating it for [`prerender-spa-plugin-next`](https://github.com/Tofandel/prerender-spa-plugin-next/issues/9)

So I'd be happy to take over

**Comment by JoshTheDerf** [comment]
Hi @Tofandel, Thanks for the interest! I'd be happy to hand it over for you to continue. I'll go ahead and add you as a maintainer to the repo and NPM, to start with, and see about transferring things over to you once we know that's working.

**Comment by JoshTheDerf** [comment]
@Tofandel Would you like me to transfer this repository over to you now?

**Comment by Tofandel** [comment]
@JoshTheDerf If that's no problem. Thanks for trusting me

**Comment by JoshTheDerf** [comment]
Sounds good. Can't transfer while you have a repo with the same name, might want to temporarily rename @Tofandel/prerenderer or delete.

**Comment by Tofandel** [comment]
Indeed, only used that to test the npm publish github action, it's deleted

**Comment by Tofandel** [comment]
Thanks for creating this amazing set of packages in the first place, they've proven very usefull, they'll be well taken care of ❤️

**Comment by JoshTheDerf** [comment]
Good to hear, you're doing a great job so far!
