### ISSUE TITLE
vue3+vite配置报错

### ISSUE THREAD

**Issue by bingbinggeng** [Tofandel/prerenderer#66]
![image](https://user-images.githubusercontent.com/124747987/218236782-4439b4b3-7619-4b69-9786-cd706b231102.png)
![image](https://user-images.githubusercontent.com/124747987/218236807-10f7ade3-7158-4199-ae51-bd34e231f0a7.png)

**Comment by Tofandel** [comment]
How about some English and some actual errors?

Closing as super low effort right now, add some more details if you're encountering an error in a supported use case, but this is a plugin for webpack and not for vite which AFAIK uses rollup

If you want to make a plugin for vite as a separate package a PR is also welcome

**Comment by Tofandel** [comment]
Vite/rolllup plugin is now available as `@prerenderer/rollup-plugin`
