### ISSUE TITLE
index.mjs is missing in the published package

### ISSUE THREAD

**Issue by arpeggiozz** [Tofandel/prerenderer#67]
Hi,

I'm using `@prerender/prerender` in a .mjs file, and I got the error `Unable to resolve path to module '@prerenderer/prerenderer'`. 

The cause is it tries to look out index.mjs as specified in exports.import in package.json, but there is no such file, only `files: ["dist", "types"]` specified in package.json. I think the index.mjs should be added into it.

**Comment by Tofandel** [comment]
Indeed, thanks for catching that

I just released a new version with the fix
