### ISSUE TITLE
Could not prerender: event 'custom-render-trigger' did not occur within 30s

### ISSUE THREAD

**Issue by clarehjh** [Tofandel/prerenderer#68]
![image](https://user-images.githubusercontent.com/83281667/228813244-b4ecc7e0-ed3d-4580-94f5-1a4f68aba9bd.png)

**Comment by Tofandel** [comment]
That message is self explanatory, if you set `renderAfterDocumentEvent` you need to trigger that event in your app when you want it to render

`document.dispatchEvent(new Event('custom-render-trigger'))`

It's not in the doc of the rollup plugin but it's in the main doc so I added that
