### ISSUE TITLE
Route detection for a Vue 3 router

### ISSUE THREAD

**Issue by idank** [Tofandel/prerenderer#71]
I currently hardcode the few dozen routes I have when setting `routes` in the config. Is there a way to generate this from a history API based router?

I realize prerenderer is meant to be framework agnostic, but I figured I'd ask before giving up.

**Comment by Tofandel** [comment]
They're both js so of course it's possible

You just need to have a file exporting the list of routes

Use that in your router and also import it in the vite config and reduce it to generate the routes you want to render in an array of path
