### ISSUE TITLE
page not clickable

### ISSUE THREAD

**Issue by pecliu** [Tofandel/prerenderer#76]
env: vue2.6 webpack

how to code

I use a lot of `v-for` with `<component :is >` and `mixin`

```vue
    <component
      v-for="item in pageConfig.componentConfig"
      :id="item.id"
      :key="item.id"
      :is="item.component"
      :cid="item.componentId"
      :tags="item.tags"
      :uid="item.id"
      :uname="item.name"
      :ref="item.id"
      :styles="item.styles"
      :configuration-data="item.configurationData"
      :interval-data-fetch-list="item.intervalDataFetchList"
      :events="item.events"
      @component-event-emitted="handleComponentEvents(arguments, item.id)"
      @defined-event-emitted="handleDefinedEvents"
    >
```

the problems is:

1. the page after prerenderer is not clickable
2. 
``` html
<div data-v-1a085488="" data-v-754880e6="" class="" id="f434c9b5-835c-4937-a5af-d70dcba100a9" style="display: block; height: 1.48rem; left: 0.54rem; position: absolute; top: 11.16rem; width: 6.36rem; word-break: break-all; z-index: 5; color: rgb(255, 255, 255); font-family: PingFangSC-Regular; font-size: 0.2rem; font-weight: normal; line-height: 0.34rem; text-align: left;"><p data-v-1a085488="" class="text-content-show" style="--backgroundColorHighlight: #638bc8; --backgroundColorGrey: #324995; --scrollBarWidth: 0.06rem;"><p data-v-1a085488="" style="white-space: pre-wrap;">     xxxxxxx  </p></p></div>
```  

becomes 

```html
<div data-v-1a085488="" data-v-754880e6="" class="" id="1d907aed-0f35-42bf-95aa-bde716054ce0" style="display: block; height: 0.99rem; left: 0.75rem; position: absolute; top: 21.24rem; width: 6.04rem; word-break: break-all; z-index: 5; color: rgb(255, 255, 255); font-family: PingFangSC-Regular; font-size: 0.2rem; font-weight: normal; line-height: 0.34rem; text-align: left;"><p data-v-1a085488="" class="text-content-show" style="--backgroundColorHighlight: #638bc8; --backgroundColorGrey: #324995; --scrollBarWidth: 0.06rem;"></p><p data-v-1a085488="" style="white-space: pre-wrap;">      xxxxxxx </p><p></p></div>
``` 

as component bellow

```vue
<template>
  <div
    :style="[styles.base,styles.fontStyle]"
    :class="[{'text-box--hide':isCarouselAnimation}]"
    @click="handleClickEvent()"
    @mouseenter="handleEvent('hover')"
  >
    <p
      :class="configurationData.isShowScrollBar ? 'text-content-show' : 'text-content-hide'"
      :style="animateOrScrollBar"
    >
      <template v-if="Array.isArray(text)">
        <p
          v-for="(item, index) in text"
          :key="index"
          class="text-content-item"
          style="white-space: pre-wrap;"
        >
          {{ item }}
        </p>
      </template>
      <template v-else>
        <p style="white-space: pre-wrap;">
        {{ text }}
        </p>
      </template>
    </p>
  </div>
</template>
```

page works fine:
https://act.supercore.qq.com/supercore/act/aeea1b2d03c3342fbaca05334cefb7587pre/index.html

page donot works fine after prerenderer:
https://act.supercore.qq.com/supercore/act/aeea1b2d03c3342fbaca05334cefb7587prerender/index.html

**Comment by Tofandel** [comment]
Your vue app is replacing the `root` component with a different id
```html
<div id="app"></div>
```
```html
<div data-v-754880e6="" class="page-content"
...
```
When your page loads, vue needs this `id="app"` to mount your app (this is what `new Vue().$mount('#app')` does), without it your app is not going to execute anything vue and is just a html page, prerendering is not a magic silver bullet, you might also want to add the `data-server-rendered` flag as documented to instruct vue it was prerendered and that it only needs to hydrate client side without recreating the dom, but that can be problematic if some of your components do direct dom manipulation

**Comment by pecliu** [comment]
> Your vue app is replacing the `root` component with no id
> 
> ```
> <div id="app"></div>
> ```
> 
> ```
> <div data-v-754880e6="" class="page-content"
> ...
> ```
> 
> When your page loads, vue needs this `id="app"` to mount your app (this is what `new Vue().$mount('#app')` does), without it your app is not going to execute anything vue and is just a html page, prerendering is not a magic silver bullet, you have to adapt your code for it achieve a correct result or plan ahead, you might also want to add the `data-server-rendered` flag as documented to instruct vue it was prerendered and that it only needs to hydrate client side without recreating the DOM, but that can be problematic if some of your components do direct DOM manipulation and you might encounter hydration errors

thank you so much
I'll try
