### ISSUE TITLE
How to use it（vue3 + vite） ?

### ISSUE THREAD

**Issue by jshuhao** [Tofandel/prerenderer#79]
![5R`%47}WWZFF
X%B~4M6(G](https://github.com/Tofandel/prerenderer/assets/43402557/a1cb7483-9b67-420e-b7ec-d0498236b2b9)
![LV1S_EA5PH@2QWA`%T_SBP8](https://github.com/Tofandel/prerenderer/assets/43402557/0084573d-fe69-4d07-b98c-739067872f2d)
![S}K${SEY~J@F2A}_C5%H1{M](https://github.com/Tofandel/prerenderer/assets/43402557/972e1237-3cae-4bc2-a75e-bf885c1c4f76)
![5R`%47}WWZFF![5R`%47}WWZFF
X%B~4M6(G](https://github.com/Tofandel/prerenderer/assets/43402557/a1cb7483-9b67-420e-b7ec-d0498236b2b9)
![LV1S_EA5PH@2QWA`%T_SBP8](https://github.com/Tofandel/prerenderer/assets/43402557/0084573d-fe69-4d07-b98c-739067872f2d)
![V6JN`{0~B(P A`B`}@AY ZA](https://github.com/Tofandel/prerenderer/assets/43402557/3c690a69-e78e-449f-a308-1a501d0774fa)

i cant't build my app , Is it my problem？i cant't build my app , Is it my problem？

**Comment by Tofandel** [comment]
> Is it my problem？

Yes, you need to check your app for errors in dev mode without prerendering first

**Comment by jshuhao** [comment]
> > Is it my problem？
> 
> Yes, you need to check your app for errors in dev mode without prerendering first

Thank you for your reply，in dev mode, it runs normally，But after build, there was an exception。
Can you help me to solve this problem Or give me some more intuitive Demo？
This is my Test  App，he looks normal。
[Uploading vite_1.rar…]()

**Comment by jshuhao** [comment]
> > > Is it my problem？
> > 
> > 
> > Yes, you need to check your app for errors in dev mode without prerendering first
> 
> Thank you for your reply，in dev mode, it runs normally，But after build, there was an exception。 Can you help me to solve this problem Or give me some more intuitive Demo？ This is my Test App，he looks normal。 

[vite_1.zip](https://github.com/Tofandel/prerenderer/files/12869976/vite_1.zip)

**Comment by Tofandel** [comment]
Sorry I will not check a project in a zip file, please provide a git repo reproducing the issue if you are still encountering problems
