### ISSUE TITLE
ERROR: Failed to set up Chrome v121.0.6167.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download

### ISSUE THREAD

**Issue by br0wsa** [Tofandel/prerenderer#89]
![Screenshot from 2024-02-22 13-17-49](https://github.com/Tofandel/prerenderer/assets/76697214/6129db05-a330-447c-ba34-48f56eda0d68)

## Issue Summary

**Problem during deployment on Vercel**

**Description:**
During the deployment of my application on Vercel, I encountered an error related to the Chrome setup. Specifically, I received an error indicating that the download of Chrome failed with error code 500.

**Context:**
I am using the "@prerenderer/renderer-puppeteer" package on VERCEL for  my application. The error occurred during the deployment process on Vercel.

**Error:**
```
Error: ERROR: Failed to set up Chrome v121.0.6167.85! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
    at file:///vercel/path0/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:58:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async downloadBrowser (file:///vercel/path0/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:87:9) {
  [cause]: Error: Download failed: server returned code 500. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chrome-linux64.zip
      at file:///vercel/path0/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:64:31
      at ClientRequest.requestCallback (file:///vercel/path0/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:42:13)
      at Object.onceWrapper (node:events:632:26)
      at ClientRequest.emit (node:events:517:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at TLSSocket.socketOnData (node:_http_client:541:22)
      at TLSSocket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9)
}
```

**Additional Note:**
The download URL provided in the error also returns a 500 error.

**To resolve the issue:**
✅ To resolve the issue, you can follow these steps:

1. Ensure you have the correct configuration for Puppeteer. Since Puppeteer v19, Chrome is saved in `~/.cache/puppeteer` instead of being inside `node_modules`.

2. If some servers don't allow reading `~/.cache/puppeteer`, it can cause the "Could not find Chrome" error. In this case, you'll need to move the `.cache` folder to the root of your project.

3. DO NOT FORGET TO ADD .cache/ to YOUR GITIGNORE FILE

4. Create a `.puppeteerrc.cjs` file at the root of your project with the following content:

```javascript
const {join} = require('path');

module.exports = {
    // Changes the cache location for Puppeteer.
    cacheDirectory: join(__dirname, '.cache', 'puppeteer'),
};

**Comment by Tofandel** [comment]
That just looks like a temporary error from the server where the chrome server is being downloaded from, doubt it has anything to do with puppeteer or this library

Your resolution would have been valid if you set PUPPETEER_SKIP_DOWNLOAD in your package.json and provided your own chrome binaries, but right now it wouldn't solve the issue you describe but it would solve a file permission issue where the ~/.cache directory is not writable (it would be a bit unorthodox to not allow the user to write to his home folder though)

From what I just tried, the url doesn't return a 500 anymore, so I'll close this
