### ISSUE TITLE
'renderer' does not exist in type 'RollupPrerenderOptions'

### ISSUE THREAD

**Issue by kingkiboots** [Tofandel/prerenderer#94]
I've tried to use prerender function with renderer option.

`prerender({
...
      renderer: "@prerenderer/renderer-puppeteer",
...
})`

But RollupPrerenderOptions has no property named 'render' since it extends Omit<PrerendererOptions, 'staticDir' | 'renderer'>.

`
// node_modules/@prerenderer/rollup-plugin/types/Options.d.ts
export interface RollupPrerenderOptions extends Omit<PrerendererOptions, 'staticDir' | 'renderer'> {
    entryPath?: string;
    fallback?: boolean | string;
    routes?: Array<string>;
    urlModifier?(url: string): string;
}
`

So I can't use @prerenderer/renderer-puppeteer option as described in Readme.

**Comment by a0s** [comment]
Yep, same issue for me

**Comment by Tofandel** [comment]
Sorry I started looking at this and then forgot

I'm not really sure why I omitted renderer as it's not omitted in webpack, and it doesn't make sense why I removed it, probably was just fighting with TS at that point. I'll add it back

@a0s Your issue is just that you are missing the puppeteer peer dependency, if you are using a package manager that does not install peer dependencies you need to add it to your list of dependencies

**Comment by a0s** [comment]
> Your issue is just that you are missing the puppeteer peer dependency, if you are using a package manager that does not install peer dependencies you need to add it to your list of dependencies (first step in the install section)

This explanation is pretty cryptic for me (
I tries both `yarn add -D @prerenderer/renderer-puppeteer` AND `yarn add @prerenderer/renderer-puppeteer` (that has no sense, just to check). The error is the same both times:
```
error during build:
RollupError: [Prerender Plugin] [plugin Prerender Plugin] Cannot find module 'puppeteer'
Require stack:
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/renderer-puppeteer/dist/Renderer.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/renderer-puppeteer/dist/index.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/renderer-puppeteer/dist/cjs.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/prerenderer/dist/Prerenderer.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/prerenderer/dist/index.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/prerenderer/dist/cjs.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/index.js
- /Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/cjs.js
    at getRollupError (file:///Users/a0s/my/proj/subproj/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///Users/a0s/my/proj/subproj/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at Object.error (file:///Users/a0s/my/proj/subproj/node_modules/rollup/dist/es/shared/node-entry.js:19593:20)
    at Object.<anonymous> (/Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js:140:34)
    at Generator.throw (<anonymous>)
    at rejected (/Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js:29:65)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-only:production" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

UPD: ok, i found this question https://stackoverflow.com/questions/53764902/cannot-find-module-puppeteer and install ` yarn add -D puppeteer`, now i've got another: 
```
error during build:
RollupError: [Prerender Plugin] [plugin Prerender Plugin] require() of ES Module /Users/a0s/my/proj/subproj/node_modules/string-width/index.js from /Users/a0s/my/proj/subproj/node_modules/cliui/build/index.cjs not supported.
Instead change the require of index.js in /Users/a0s/my/proj/subproj/node_modules/cliui/build/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at getRollupError (file:///Users/a0s/my/proj/subproj/node_modules/rollup/dist/es/shared/parseAst.js:394:41)
    at error (file:///Users/a0s/my/proj/subproj/node_modules/rollup/dist/es/shared/parseAst.js:390:42)
    at Object.error (file:///Users/a0s/my/proj/subproj/node_modules/rollup/dist/es/shared/node-entry.js:19593:20)
    at Object.<anonymous> (/Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js:140:34)
    at Generator.throw (<anonymous>)
    at rejected (/Users/a0s/my/proj/subproj/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js:29:65)
```

**Comment by Tofandel** [comment]
Can you open a new issue with your usage/reproduction?
Those deps in the error message are not dependencies of the package, the package itself ships with both ESM and CJS support
